"""empty message

Revision ID: 0ac4fc98fbdc
Revises: 6a0ff6a3088b
Create Date: 2020-11-05 05:23:30.623078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac4fc98fbdc'
down_revision = '6a0ff6a3088b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('bandId', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venueId', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('when', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'when')
    op.drop_column('Show', 'venueId')
    op.drop_column('Show', 'bandId')
    # ### end Alembic commands ###
