"""empty message

Revision ID: 3f99c3654cf9
Revises: e79e7e1cd765
Create Date: 2020-11-06 20:54:19.503783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f99c3654cf9'
down_revision = 'e79e7e1cd765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_venueId_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_bandId_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Show', 'venueId')
    op.drop_column('Show', 'bandId')
    op.drop_column('Show', 'when')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('when', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('bandId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('venueId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_bandId_fkey', 'Show', 'Artist', ['bandId'], ['id'])
    op.create_foreign_key('Show_venueId_fkey', 'Show', 'Venue', ['venueId'], ['id'])
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'start_time')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
