"""empty message

Revision ID: c0ee1522a6fd
Revises: 0ac4fc98fbdc
Create Date: 2020-11-06 14:57:42.477862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ee1522a6fd'
down_revision = '0ac4fc98fbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Show', 'Artist', ['bandId'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venueId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    # ### end Alembic commands ###
